[package]
name = "solana-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
solana-client = "1.18.14"
solana-sdk = "1.18.14"
hyper = "1.6.0"
